variables:
        GIT_SSL_NO_VERIFY: "1"

stages:
        - compile
        - deploy

pdf:
        stage: compile
        image: schickling/latex
        script:
                pwd
                ls -al
                cat compile.sh
